#if !canImport(ObjectiveC)
import XCTest

extension MediaUtilityTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MediaUtilityTests = [
        ("testDecodeTimestamp", testDecodeTimestamp),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MediaUtilityTests.__allTests__MediaUtilityTests),
    ]
}
#endif
